userknn_model:
  online_mode: True
  online: 'data/userknn_model.dill'
  offline: 'data/userknn_recos.csv'

popular_model:
  online: 'data/popular_model.dill'
  offline: 'data/popular_recos.csv'

lightfm_model:
  online: 'data/lightfm_model.dill'

popular_by_age_model:
  offline: 'data/popular_by_age_model.csv'

original_data:
  interactions: 'data/kion_train/interactions.csv'
  users: 'data/kion_train/users.csv'
  items: 'data/kion_train/items.csv'
